# Project: Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../programming/sharkGame/sharkGame/board.o ../../../programming/sharkGame/sharkGame/main.o
LINKOBJ  = ../../../programming/sharkGame/sharkGame/board.o ../../../programming/sharkGame/sharkGame/main.o
LIBS     = -L"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib" -L"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../programming/sharkGame/sharkGame/board.o: ../../../programming/sharkGame/sharkGame/board.c
	$(CC) -c ../../../programming/sharkGame/sharkGame/board.c -o ../../../programming/sharkGame/sharkGame/board.o $(CFLAGS)

../../../programming/sharkGame/sharkGame/main.o: ../../../programming/sharkGame/sharkGame/main.c
	$(CC) -c ../../../programming/sharkGame/sharkGame/main.c -o ../../../programming/sharkGame/sharkGame/main.o $(CFLAGS)
