# Project: week07_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main1.o
LINKOBJ  = main1.o
LIBS     = -L"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib" -L"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/soyun/OneDrive/πŸ≈¡ »≠∏È/programming/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = week07_1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main1.o: main1.c
	$(CC) -c main1.c -o main1.o $(CFLAGS)
